-- School Attendance Verification System Database Schema (PostgreSQL for Supabase)

-- Drop tables in reverse order of foreign key dependencies to prevent errors
-- Using CASCADE automatically drops all associated triggers, constraints, and dependencies.
DROP TABLE IF EXISTS attendance_reports CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS live_locations CASCADE;
DROP TABLE IF EXISTS attendance_submissions CASCADE;
DROP TABLE IF EXISTS scheduled_classes CASCADE;
DROP TABLE IF EXISTS lecture_halls CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS func_prevent_attendance_update() CASCADE;
DROP FUNCTION IF EXISTS func_prevent_attendance_delete() CASCADE;

-- ============================================
-- 1. USERS TABLE (Admins and Lecturers)
-- ============================================
CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    full_name VARCHAR(100),
    phone VARCHAR(15),
    role VARCHAR(20) DEFAULT 'lecturer' CHECK (role IN ('lecturer', 'admin')),
    department VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_username ON users(username);
CREATE INDEX idx_role ON users(role);

-- ============================================
-- 2. LECTURE HALLS / CLASSROOMS TABLE
-- Predefined campuses/venues with 3D coordinates (lat, lon, altitude)
-- ============================================
CREATE TABLE lecture_halls (
    hall_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_name VARCHAR(100) NOT NULL,
    hall_code VARCHAR(20) UNIQUE,
    latitude NUMERIC(10, 8) NOT NULL,
    longitude NUMERIC(11, 8) NOT NULL,
    altitude_meters NUMERIC(6, 2) DEFAULT 0.00, -- Height reference (meters)
    tolerance_radius_meters INT DEFAULT 50,     -- Horizontal geofence limit
    altitude_tolerance_meters NUMERIC(4, 2) DEFAULT 3.00, -- Vertical geofence limit (approx 1 floor height)
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_hall_code ON lecture_halls(hall_code);

-- ============================================
-- 3. SCHEDULED CLASSES TABLE
-- Class slots assigned to lecturers at specific lecture halls
-- ============================================
CREATE TABLE scheduled_classes (
    class_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id INT NOT NULL REFERENCES users(user_id),
    hall_id INT NOT NULL REFERENCES lecture_halls(hall_id),
    course_code VARCHAR(15) NOT NULL, -- e.g., 'CSC 401'
    course_title VARCHAR(100),
    scheduled_start_time TIME NOT NULL,
    scheduled_end_time TIME NOT NULL,
    scheduled_date DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
    created_by INT REFERENCES users(user_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_lecturer_date ON scheduled_classes(lecturer_id, scheduled_date);
CREATE INDEX idx_scheduled_date ON scheduled_classes(scheduled_date);

-- ============================================
-- 4. ATTENDANCE SUBMISSIONS TABLE
-- Logs class check-ins and 3D verification status
-- ============================================
CREATE TABLE attendance_submissions (
    submission_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INT NOT NULL REFERENCES scheduled_classes(class_id),
    lecturer_id INT NOT NULL REFERENCES users(user_id),
    submitted_latitude NUMERIC(10, 8) NOT NULL,
    submitted_longitude NUMERIC(11, 8) NOT NULL,
    submitted_altitude NUMERIC(6, 2) NOT NULL,
    assigned_latitude NUMERIC(10, 8) NOT NULL,
    assigned_longitude NUMERIC(11, 8) NOT NULL,
    assigned_altitude NUMERIC(6, 2) NOT NULL,
    server_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    distance_from_assigned_location NUMERIC(10, 2) NOT NULL,
    location_accuracy_meters INT,
    
    -- Verification outcomes
    spatial_validation VARCHAR(10) NOT NULL CHECK (spatial_validation IN ('PASS', 'FAIL')),
    temporal_validation VARCHAR(10) NOT NULL CHECK (temporal_validation IN ('PASS', 'FAIL')),
    altitude_validation VARCHAR(10) NOT NULL CHECK (altitude_validation IN ('PASS', 'FAIL')),
    verification_status VARCHAR(20) DEFAULT 'PENDING' CHECK (verification_status IN ('VERIFIED', 'OUT_OF_RANGE', 'INVALID_TIME', 'INVALID_ALTITUDE', 'PENDING', 'REJECTED')),
    
    submission_description TEXT,
    is_anomalous BOOLEAN DEFAULT FALSE,
    anomaly_reason VARCHAR(255),
    
    -- Admin review fields
    reviewed_by INT REFERENCES users(user_id),
    review_notes TEXT,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_verification_status ON attendance_submissions(verification_status);
CREATE INDEX idx_lecturer_timestamp ON attendance_submissions(lecturer_id, server_timestamp);

-- ============================================
-- 5. LIVE LOCATIONS TABLE
-- Stores latest real-time tracking ping for active tracking during class hours
-- ============================================
CREATE TABLE live_locations (
    ping_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id INT UNIQUE NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    latitude NUMERIC(10, 8) NOT NULL,
    longitude NUMERIC(11, 8) NOT NULL,
    altitude NUMERIC(6, 2) NOT NULL,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 6. AUDIT LOGS TABLE
-- Tracks critical system updates for accountability
-- ============================================
CREATE TABLE audit_logs (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    action VARCHAR(100) NOT NULL,
    table_name VARCHAR(50),
    record_id INT,
    old_value TEXT,
    new_value TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 7. SYSTEM SETTINGS TABLE
-- ============================================
CREATE TABLE system_settings (
    setting_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_value TEXT,
    setting_type VARCHAR(20) DEFAULT 'string' CHECK (setting_type IN ('string', 'integer', 'boolean', 'decimal')),
    description TEXT,
    updated_by INT REFERENCES users(user_id),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 8. ATTENDANCE REPORTS TABLE
-- Aggregated report data for school management
-- ============================================
CREATE TABLE attendance_reports (
    report_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id INT NOT NULL REFERENCES users(user_id),
    report_date DATE NOT NULL,
    total_classes_scheduled INT DEFAULT 0,
    total_classes_verified INT DEFAULT 0,
    total_classes_failed INT DEFAULT 0,
    verification_percentage NUMERIC(5, 2),
    UNIQUE (lecturer_id, report_date)
);

-- ============================================
-- INITIAL SEED DATA
-- ============================================

-- Passwords: admin123 and lecturer123 hashed using SHA-256
INSERT INTO users (username, password, email, full_name, role, department) VALUES
('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'admin@school.edu.ng', 'System Administrator', 'admin', 'ICT'),
('lecturer1', 'a4c3fcb625ccf255765afd5e3548839e8a2de6c587d7125dfba735dda69dbe22', 'emeka.okafor@school.edu.ng', 'Dr. Emeka Okafor', 'lecturer', 'Computer Science'),
('lecturer2', 'a4c3fcb625ccf255765afd5e3548839e8a2de6c587d7125dfba735dda69dbe22', 'chioma.adeyemi@school.edu.ng', 'Prof. Chioma Adeyemi', 'lecturer', 'Mathematics'),
('lecturer3', 'a4c3fcb625ccf255765afd5e3548839e8a2de6c587d7125dfba735dda69dbe22', 'amara.ibrahim@school.edu.ng', 'Dr. Amara Ibrahim', 'lecturer', 'Physics');

-- Insert lecture halls with 3D references: (lat, lon, altitude_meters, tolerance_radius, altitude_tolerance)
INSERT INTO lecture_halls (hall_name, hall_code, latitude, longitude, altitude_meters, tolerance_radius_meters, altitude_tolerance_meters, description) VALUES
('Main Auditorium (Ground Floor)', 'AUD-MAIN', 6.52440000, 3.37920000, 0.00, 50, 3.00, 'Main auditorium, Ground Floor level'),
('Science Lab Hall B (2nd Floor)', 'LAB-SCI-B', 6.55210000, 3.35210000, 6.00, 30, 2.50, 'Physics lab on the 2nd Floor level (approx 6 meters high)'),
('ETF Seminar Room (3rd Floor)', 'ETF-SEM', 9.07650000, 7.39860000, 9.00, 40, 2.50, 'ETF Building, 3rd Floor Seminar Room'),
('Science Block RM 5 (1st Floor)', 'SCI-RM5', 6.52480000, 3.37950000, 3.00, 30, 2.50, 'Science block, First Floor level');

-- Insert classes scheduled for today (CURRENT_DATE in Postgres)
INSERT INTO scheduled_classes (lecturer_id, hall_id, course_code, course_title, scheduled_start_time, scheduled_end_time, scheduled_date, status) VALUES
(2, 1, 'CSC 401', 'Compiler Construction', '09:00:00', '11:00:00', CURRENT_DATE, 'scheduled'),
(2, 2, 'CSC 415', 'Database Systems II', '14:00:00', '16:00:00', CURRENT_DATE, 'scheduled'),
(3, 1, 'MTH 101', 'Algebra and Trigonometry', '10:00:00', '12:00:00', CURRENT_DATE, 'scheduled'),
(4, 3, 'PHY 202', 'General Physics II', '09:00:00', '12:00:00', CURRENT_DATE, 'scheduled');

-- Insert system settings
INSERT INTO system_settings (setting_key, setting_value, setting_type, description) VALUES
('max_distance_tolerance_meters', '50', 'integer', 'Default geofence radius for check-ins'),
('enable_anomaly_detection', 'true', 'boolean', 'Enable impossible travel check'),
('timezone', 'Africa/Lagos', 'string', 'System timezone');

-- ============================================
-- PL/pgSQL TRIGGERS FOR DATA IMMUTABILITY
-- ============================================

CREATE OR REPLACE FUNCTION func_prevent_attendance_update()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.submitted_latitude <> NEW.submitted_latitude OR 
       OLD.submitted_longitude <> NEW.submitted_longitude OR
       OLD.submitted_altitude <> NEW.submitted_altitude OR
       OLD.distance_from_assigned_location <> NEW.distance_from_assigned_location OR
       OLD.server_timestamp <> NEW.server_timestamp THEN
        RAISE EXCEPTION 'Attendance check-in records are immutable and cannot be updated';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER prevent_attendance_update
BEFORE UPDATE ON attendance_submissions
FOR EACH ROW
EXECUTE FUNCTION func_prevent_attendance_update();

-- Prevent deletion of submissions
CREATE OR REPLACE FUNCTION func_prevent_attendance_delete()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Attendance check-in records cannot be deleted for audit trail compliance';
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER prevent_attendance_delete
BEFORE DELETE ON attendance_submissions
FOR EACH ROW
EXECUTE FUNCTION func_prevent_attendance_delete();
