services:
  - type: web
    name: muyiwafsv
    env: docker
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: postgres
